### ISSUE TITLE
Triangulation fails for certain vertex positions

### ISSUE THREAD

**Issue by TheCelticGuy** [ScottRTAnderson/Delaunay-Triangulation#1]
Hello

I been running the code using just 4 points, and moving them randomly as I generate the mesh. 

Turns out the algorithm fails in the event 3 points that should create a polygon are almost colinear, this results in a vertex being disconnected:

![image](https://user-images.githubusercontent.com/33559521/227750062-e5c76b90-6c02-46df-bad5-6f281fc739fe.png)

An animation where it happens for a brief moment - blink and you'll miss it (most right point gets disconnected):

![a](https://user-images.githubusercontent.com/33559521/227750094-628425ce-8f9f-4b03-b58a-d9456855a50e.gif)

I have no idea why it happens or how to fix it however. Perhaps you might recognise what is causing the problem?

**EDIT:**

Managed to find a data setup to replicate it, these 4 points results in an incorrect triangulation - ends up with a vertex left out of the triangulation:

![image](https://user-images.githubusercontent.com/33559521/227754171-1d1cf38f-d8d2-4271-9828-8d04022eccc3.png)

Can you see if you can replicate the same result encase i've just done something dumb on my end?

Further testing, it seems to be that it finds a triangulation for a 4th point that does not connect to two other points but rather the super triangle. So when you then delete all triangles sharing a vertex with the super triangle it becomes a lone vertex like you see here (the red dotted line is what should connect if it was to work correctly:

![image](https://user-images.githubusercontent.com/33559521/227755200-f1b35558-be21-46cf-8403-519bd9c19ed8.png)

**Comment by ScottyRAnderson** [comment]
Hello

Really appreciate you pointing this out, I think I have an idea as to what might happening but I cannot say for sure until I get home and test this, currently on a train but will look at this asap.

Cheers again.

**Comment by ScottyRAnderson** [comment]
Hello again,

Apologies for the late response. I have emulated the conditions as you have described them for a sequence of four points, and I also recieved the problem you identified, as suspected, it has to do with the size of the initial supra-triangle.

When I increase the size of the supra-triangle we can see the triangulation perfom as expected:

https://user-images.githubusercontent.com/50529114/228035827-b9aeacc5-c1a4-4745-91ce-6ddcf39b09e1.mp4

### Reasoning
This isn't a problem with the algorithm, or a bug for that matter, it is simply the fact that when inspecting a given point, the neighbouring circum-circles generated by neighbouring points aren't large enough to encompass the inspected point and therefore no bad triangles are identified on that pass, thus resulting in no new polygons being formed with that point, causing the case whereby the point appears on its own.

If we however increase the size of the supra-triangle, this in turn increases the size of any circum-circles that use the verticies of the supra-triangle. If we increase the size of the supra-triangle enough, we can get the circum-circles to encompass our extreme point as displayed in the video below, observe the moment that the circum-circle is large enough to cover the far right point:

https://user-images.githubusercontent.com/50529114/228053635-58b6139c-dd0e-40b7-b04b-b14456b5234d.mp4

(Note, it may be hard to see this happening due to the resolution of the debug circle and the fact that on this large scale only a minimal inclusion may be seen, but enough to identify the bad triangle)

### Solution
So the solution, is to simply increase the size of the supra-triangle to suit a given scenario, there is likely a more concrete reasoning and solution but given my limited time at the moment this is the best I can think of...
I am aware that it's not ideal, but should be sufficient to fix the problem in 99% of scenarios.

You can either implement your own supra-triangle size modifier variable for more dynamic adjustment, or simply increase this **margin** parameter already in the _'DelaunayHelper.cs'_ class. I found a value of _20_ worked well for most situations...

But you could also just set this value to a really high number like _1500_ at little to no performance impact and the triangulation would work in any extreme case.
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/50529114/228057070-4b0cd04b-1aed-477d-afe7-795d08f53da5.png">

### Testing
Below is a test of extreme triangle cases with a **margin** of _1000_:

https://user-images.githubusercontent.com/50529114/228060295-03bb2484-4be5-4c74-b439-a67c46a97ef8.mp4

I'll look a bit further into why this is happening, see if I can find a more solid solution, but hopefully this works for you for now.
Thinking about it now though, I think this is a flaw of the Bowyer Watson algorithm as opposed to my implementation, and prehaps a different algorithm should be investigated instead.

As a final note, I want to mention that in the most extreme cases whereby three points lie in the same line or very close to, it will be impossible for any point to lie in a neighbouring circum-circle and therefore naturally the algorithm will fail.

Thanks again for identifying this problem, apologies for my rather lengthy response, I hope it helps.
Cheers
